homepage:
    path: /
    controller: Symfony5\Controller\HomepageController::list

product_import:
    path: product/import/
    controller: Symfony5\Controller\ImportController::import

product_search:
    path: product/search/
    controller: Symfony5\Controller\SearchController::search